site_name: Artificial Intelligence (AI) with Python
site_url: https://mydomain.org/mysite
site_author: Joshua OhYQ
copyright: "Copyright &copy; 2025 Joshua OhYQ"

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.footnote.tooltips
    - content.tooltips
  
  icon:
    admonition:
      note: material/note-outline
      abstract: material/format-list-checks
      info: material/information
      tip: material/lightbulb-on
      success: material/check-bold
      question: material/help-circle
      warning: material/alert
      failure: material/close-thick
      danger: material/flash
      bug: material/bug
      example: material/test-tube
      quote: material/format-quote-close
    annotation: material/plus-circle
    
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://joshuaohyq.github.io/AI-Python/
      name: Joshua Oh's GitHub
      
extra_css:
  - stylesheets/extra.css
  
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js  
  
markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.blocks.caption     
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - attr_list
  - pymdownx.snippets
  
nav:
  - Home: index.md
  - Fundamentals:
    - "First Order Logic and Expert Systems": Chapter1.md
    - "Fuzzy Logic and Fuzzy Inference Systems": Chapter2.md
  - Resources:
    - "References": references.md
