name: Deploy MkDocs

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: .cache
          key: mkdocs-material-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            mkdocs-material-${{ runner.os }}-

      - name: Install dependencies
        run: pip install --upgrade mkdocs-material

      - name: Build site
        run: mkdocs build

      - name: Upload artifact
        uses: actions/upload-artifact@v4 
          name: github-pages
          path: site/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  
